# Generated by Django 2.1.3 on 2019-01-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='price_range',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
