# Generated by Django 2.1.3 on 2019-01-04 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20190102_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='group',
            name='price_range',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
