# Generated by Django 2.1.3 on 2019-01-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20190104_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member_ids',
            field=models.CharField(blank='', default='', max_length=5),
        ),
    ]
