# Generated by Django 2.1.3 on 2019-01-09 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20190104_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member_ids',
            field=models.CharField(max_length=5, validators=[django.core.validators.int_list_validator]),
        ),
    ]
