# Generated by Django 2.1.3 on 2019-01-09 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20190109_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member_ids',
            field=models.CharField(blank=True, default='', max_length=5, validators=[django.core.validators.int_list_validator]),
        ),
    ]
