# Generated by Django 2.1.3 on 2018-11-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='categories',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
